export const mockCars = [
  {
    id: "1",
    name: "Toyota Camry",
    provider: "Enterprise",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&auto=format&fit=crop",
    price: 45,
    rating: 4.8,
    type: "Sedan",
    transmission: "Automatic",
    fuelType: "Hybrid",
    seats: 5,
    description: "Comfortable mid-size sedan perfect for business trips or family vacations. Excellent fuel economy and smooth ride quality.",
    features: ["Bluetooth", "Backup Camera", "Apple CarPlay", "Cruise Control", "USB Charging"],
    insurance: 15,
    mileage: "Unlimited"
  },
  {
    id: "2",
    name: "Honda CR-V",
    provider: "Hertz",
    image: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&auto=format&fit=crop",
    price: 65,
    rating: 4.7,
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Gasoline",
    seats: 5,
    description: "Spacious SUV with plenty of cargo room. Ideal for outdoor adventures and family trips.",
    features: ["AWD", "Sunroof", "Navigation", "Heated Seats", "Power Liftgate"],
    insurance: 20,
    mileage: "Unlimited"
  },
  {
    id: "3",
    name: "BMW 3 Series",
    provider: "Sixt",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop",
    price: 95,
    rating: 4.9,
    type: "Luxury",
    transmission: "Automatic",
    fuelType: "Gasoline",
    seats: 5,
    description: "Premium luxury sedan with sophisticated styling and dynamic performance. Perfect for making an impression.",
    features: ["Leather Seats", "Premium Sound", "Adaptive Cruise", "Parking Assist", "Wireless Charging"],
    insurance: 30,
    mileage: "300 mi/day"
  },
  {
    id: "4",
    name: "Ford Escape",
    provider: "Budget",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop",
    price: 55,
    rating: 4.6,
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Hybrid",
    seats: 5,
    description: "Compact SUV with excellent fuel efficiency and modern technology features.",
    features: ["Lane Assist", "Blind Spot Monitor", "Keyless Entry", "Dual Climate", "Roof Rails"],
    insurance: 18,
    mileage: "Unlimited"
  },
  {
    id: "5",
    name: "Tesla Model 3",
    provider: "Hertz",
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&auto=format&fit=crop",
    price: 85,
    rating: 4.9,
    type: "Electric",
    transmission: "Automatic",
    fuelType: "Electric",
    seats: 5,
    description: "All-electric sedan with cutting-edge technology and impressive performance. Zero emissions driving.",
    features: ["Autopilot", "Supercharger Access", "Premium Interior", "Glass Roof", "Over-the-Air Updates"],
    insurance: 25,
    mileage: "300 mi charge"
  },
  {
    id: "6",
    name: "Chevrolet Tahoe",
    provider: "Enterprise",
    image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&auto=format&fit=crop",
    price: 110,
    rating: 4.7,
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Gasoline",
    seats: 8,
    description: "Full-size SUV with three rows of seating. Perfect for large groups or family road trips.",
    features: ["4WD", "Third Row", "Towing Package", "Entertainment System", "Power Running Boards"],
    insurance: 35,
    mileage: "Unlimited"
  },
  {
    id: "7",
    name: "Hyundai Elantra",
    provider: "Thrifty",
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format&fit=crop",
    price: 38,
    rating: 4.5,
    type: "Economy",
    transmission: "Automatic",
    fuelType: "Gasoline",
    seats: 5,
    description: "Budget-friendly sedan with modern styling and good fuel economy. Great value for money.",
    features: ["Bluetooth", "USB Ports", "Air Conditioning", "Power Windows", "Digital Display"],
    insurance: 12,
    mileage: "Unlimited"
  },
  {
    id: "8",
    name: "Mercedes E-Class",
    provider: "Sixt",
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&auto=format&fit=crop",
    price: 120,
    rating: 4.9,
    type: "Luxury",
    transmission: "Automatic",
    fuelType: "Gasoline",
    seats: 5,
    description: "Elegant luxury sedan combining comfort, technology, and performance. Ultimate business class travel.",
    features: ["Massage Seats", "Burmester Sound", "360 Camera", "Air Suspension", "Ambient Lighting"],
    insurance: 40,
    mileage: "250 mi/day"
  }
];

export const mockBookings = [
  {
    id: "b1",
    carId: "1",
    carName: "Toyota Camry",
    provider: "Enterprise",
    pickupLocation: "LAX Airport",
    pickupDate: "2025-01-15",
    returnDate: "2025-01-18",
    totalCost: 180,
    status: "completed"
  },
  {
    id: "b2",
    carId: "3",
    carName: "BMW 3 Series",
    provider: "Sixt",
    pickupLocation: "Miami Downtown",
    pickupDate: "2025-02-10",
    returnDate: "2025-02-12",
    totalCost: 240,
    status: "upcoming"
  }
];
